# give your workflow a name
name: Test and Deploy

# create a trigger to start your workflow running
on:
  push:
    branches:
      - main

# create jobs to run when trigger happens
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'my_db'
          postgresql user: 'test_user'
          postgresql password: 'test_password'
      - name: Run tests
        run: PGDATABASE=my_db PGUSER=test_user PGPASSWORD=test_password npm test

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: server-example-cgf
          heroku_email: c.g.fennelly@gmail.com
